export const LOCALITIES = [
    {id: 1, name: "Aguaray"},
    {id: 2, name: "Aguas Blancas"},
    {id: 3, name: "Angastaco"},
    {id: 4, name: "Animaná"},
    {id: 5, name: "Apolinario Saravia"},
    {id: 6, name: "Cachi"},
    {id: 7, name: "Cafayate"},
    {id: 8, name: "Campo Quijano"},
    {id: 9, name: "Campo Santo"},
    {id: 10, name: "Capital"},
    {id: 11, name: "Cerrillos"},
    {id: 12, name: "Chicoana"},
    {id: 13, name: "Colonia Santa Rosa"},
    {id: 14, name: "Coronel Moldes"},
    {id: 15, name: "El Bordo"},
    {id: 16, name: "El Carril"},
    {id: 17, name: "El Galpón"},
    {id: 18, name: "El Jardín"},
    {id: 19, name: "El Potrero"},
    {id: 20, name: "El Quebrachal"},
    {id: 21, name: "El Tala"},
    {id: 22, name: "Embarcación"},
    {id: 23, name: "General Güemes"},
    {id: 24, name: "General Pizzarro"},
    {id: 25, name: "General Mosconi"},
    {id: 26, name: "General Ballivián"},
    {id: 27, name: "Guachipas"},
    {id: 28, name: "Hipólito Yrigoyen"},
    {id: 29, name: "Iruya"},
    {id: 30, name: "Isla de Cañas"},
    {id: 31, name: "Joaquín V. Gonzalez"},
    {id: 32, name: "La Caldera"},
    {id: 33, name: "La Candelaria"},
    {id: 34, name: "La Merced"},
    {id: 35, name: "La Poma"},
    {id: 36, name: "La Viña"},
    {id: 37, name: "Las Lajitas"},
    {id: 38, name: "Los Toldos"},
    {id: 39, name: "Molinos"},
    {id: 40, name: "Nazareno"},
    {id: 41, name: "Otro"},
    {id: 42, name: "Payogasta"},
    {id: 43, name: "Profesor Salvador Mazza"},
    {id: 44, name: "Río Piedras"},
    {id: 45, name: "Rivadavia Banda Norte"},
    {id: 46, name: "Rivadavia Banda Sur"},
    {id: 47, name: "Rosario de la Frontera"},
    {id: 48, name: "Rosario de Lerma"},
    {id: 49, name: "San Antonio de los Cobres"},
    {id: 50, name: "San Carlos"},
    {id: 51, name: "San José de Metán"},
    {id: 52, name: "San Lorenzo"},
    {id: 53, name: "San Ramón de la Nueva Orán"},
    {id: 54, name: "Santa Victoria Este"},
    {id: 55, name: "Santa Victoria Oeste"},
    {id: 56, name: "Seclantás"},
    {id: 57, name: "Tartagal"},
    {id: 58, name: "Tolar Grande"},
    {id: 59, name: "Urundel"},
    {id: 60, name: "Vaqueros"}
];
